### ISSUE TITLE
Account Recovery

### ISSUE THREAD

**Issue by harirubix** [rubixchain/rubixgoplatform#157]
The objective of this issue is to track the account recovery module.   To achieve complete account recovery , we need to add 3 features

- [x] Key recovery using mnemonics - ONLY FOR BIP39 keys ! The mnemonic file is currently stored as mnemonic.txt in DID folder. Nodes can backup the mnemonic key and regenerate the same BIP key pairs by passing same mnemonic as parameter -mnemonicKeyFile for createDID API
- [x]  Data recovery - Pinning as a service node to provide token and token chain storage for user.  After recovering account , authenticate to pinning service node to recover the network state
- [x] IPFS PeerID - Inform new address to network by signing on new PeerID and publishing to network.

**Comment by Allen-Cherian** [comment]
Data recovery : Pinning as a service node to provide token and token storage for user. Has been merged with the PR : https://github.com/rubixchain/rubixgoplatform/pull/189

**Comment by harirubix** [comment]
Closing . Features supported from Rubix [v0.0.18](https://github.com/rubixchain/rubixgoplatform/releases/tag/v0.0.18) through #204
