### ISSUE TITLE
Getting error when creating Type 4 (BIP) DID

### ISSUE THREAD

**Issue by saishibunb** [rubixchain/rubixgoplatform#181]
2024/06/25 16:02:19 http: panic serving 127.0.0.1:56026: runtime error: invalid memory address or nil pointer dereference
goroutine 122 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1854 +0xbf
panic({0x100dae0c0, 0x10220cf30})
        /usr/local/go/src/runtime/panic.go:890 +0x263
github.com/rubixchain/rubixgoplatform/wrapper/ensweb.(*Server).ParseMultiPartForm(0xc0003623c0?, 0xc00ceac180, {0xc000046c00, 0x30})
        /go/src/rubixgoplatform/wrapper/ensweb/handler.go:261 +0x183
github.com/rubixchain/rubixgoplatform/server.(*Server).APICreateDID(0xc000376300, 0x0?)
        /go/src/rubixgoplatform/server/did.go:46 +0x1cc
github.com/rubixchain/rubixgoplatform/wrapper/ensweb.basicHandleFunc.func1({0x1011b03c0?, 0xc0000dc540?}, 0xc000324800)
        /go/src/rubixgoplatform/wrapper/ensweb/handler.go:173 +0x74
net/http.HandlerFunc.ServeHTTP(0xc000324700?, {0x1011b03c0?, 0xc0000dc540?}, 0xc0000879e8?)
        /usr/local/go/src/net/http/server.go:2122 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00037c240, {0x1011b03c0, 0xc0000dc540}, 0xc000324500)
        /root/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
net/http.serverHandler.ServeHTTP({0x1011ac8d0?}, {0x1011b03c0, 0xc0000dc540}, 0xc000324500)
        /usr/local/go/src/net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc004dc4000, {0x1011b13e8, 0xc00cf9f950})
        /usr/local/go/src/net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3089 +0x5ed

**Comment by harirubix** [comment]
Problem with input data format (wrong format was being used).  Issue #184 adds client side validation to handle errors better.
