### ISSUE TITLE
Mnemonic file path Issue

### ISSUE THREAD

**Issue by Maneesha-rubix** [rubixchain/rubixgoplatform#223]
To re-create a DID using its corresponding mnemonic key, we have to pass the mnemonic file path to the flag `-mnemonicKeyFile` with command `createdid`. But if the path is not passed correctly, it creates a new mnemonic key with a new DID. But it should through an error stating that the provided path does not contain any mnemonic key file.

**Comment by thewebchap** [comment]
Makes sense .  Currently it throws a warning statement & creates anyway .  Should we continue to create new key if `mnemonicKeyFile` value is default `-mnemonic.txt `(this is value path added if -mnemonicKeyFile is not mentioned ) ? And If path mentioned is not default one , throw error and exit without creation .
