### ISSUE TITLE
Fractionalization of RBTs

### ISSUE THREAD

**Issue by harirubix** [rubixchain/rubixgoplatform#43]
This issue is to split RBT tokens to fractions by generating 2 child tokens from parent token. Both nodes to hold (pin) the parent token in order to avoid further transfer of parent token. RACFT ( Fungible Tokens) could have a 1-n split extension of this. The lowest possible split value is 0.01 RBT.

**Comment by KiranHRubix** [comment]
PR related to this issue #54

**Comment by harirubix** [comment]
Closed by #54
