### ISSUE TITLE
APIs for smart contract and RAC Token interaction

### ISSUE THREAD

**Issue by harirubix** [rubixchain/rubixgoplatform#46]
Set of APIs to interact with  smart contract .

1. generateContract(filelocation, RBT)
2. publishContract(contractTokenHash)
3. deployContract(contractTokenHash)
4. executeContract(contractTokenHash, contractTokenChain, function , input)
5. fetchContract(contractTokenHash , datalevel: lite/full)

**Comment by gklps** [comment]
[PR](https://github.com/rubixchain/rubixgoplatform/pull/40)
