### ISSUE TITLE
Receiver offline ; quorum pin tokenstate

### ISSUE THREAD

**Issue by harirubix** [rubixchain/rubixgoplatform#48]
Tokenstate is essentially { tokenhash.tokenchainhash } at time when the current sender received a token. Now, when the sender initiates a transaction, the quorum for this transaction pins tokenstate to mark that the ‘tokenstate’ is ‘exhausted’. If a double spend attempt is initiated for the same token , the new quorum will check for token state in ipfs and therefore block double spend attempt

![Receiver_offline_quorum_pin_tokenstate](https://github.com/rubixchain/rubixgoplatform/assets/130964671/06745d26-7cf9-441b-8f06-fcf87b24b65e)

**Comment by KiranHRubix** [comment]
@harirubix 

In this logic we also have to consider the fact that the latest blocks will be self signed blocks,

Like Pledged BLock, Un pledged Block,

**Comment by KiranHRubix** [comment]
I will be handling the scenarios in code, But just a heads up

**Comment by KiranHRubix** [comment]
This issue was handled in PR #63
