### ISSUE TITLE
restructure use of ens libraries in rubixgoplatform

### ISSUE THREAD

**Issue by harirubix** [rubixchain/rubixgoplatform#79]
Rubix go platform uses ens libraries which sometimes make it difficult to add new functionalities since it requires to update the package.  The libraries can be used as a wrapper function inside rubixgoplatform core like a utils to make it easy to add new funtions and/or use different libraries.

**Comment by gklps** [comment]
#80 - resolving

**Comment by harirubix** [comment]
Closed by #80
