### ISSUE TITLE
Bug - Parts token transfer Failing

### ISSUE THREAD

**Issue by KiranHRubix** [rubixchain/rubixgoplatform#86]
when trying to send parts token , i.e. value of 0.1 and so on  , txn fails.

**Comment by KiranHRubix** [comment]
Investigated the issue, by checking the logs and see that the parent RBT token ( specifically whole token), are not being synced properly to the quorum node to verify the part token authenticity.
<img width="1156" alt="Screenshot 2023-12-04 at 10 01 13 PM" src="https://github.com/rubixchain/rubixgoplatform/assets/94098538/4e3ee434-1a0c-4a38-818b-bbdb3f52a29e">

**Comment by KiranHRubix** [comment]
Analysing the code base for the same by checking loggers, The issue is focussed around the method syncParentToken() part of the core module , in file quorum_validation.go

The issue is mainly seen only when the parent token is a Whole RBT token and not a part token.

further investigation of code showed the exact areas where the issue was happening. 

lines are as hown below 

https://github.com/rubixchain/rubixgoplatform/blob/7d47c55c6b77b2a12ef47ea7a7d8961b795219c3/core/quorum_validation.go#L64-L78

**Comment by KiranHRubix** [comment]
For whole parent token token value is and token type ( diffrent type of tokens like part token, data token smart contract token) are set .

But due to a bug in operation condition in the if clause, the token type of parent token whose value is of 1 is being re written  by the logic inside the if clause.

explanation 

- Transferring an amount of 0.1 where the part token was created by splitting a whole token to 0.1 and 0.9.
- the quorum and receiver has to sync the parent whole token to verify the split and lock the token by multi pinning so as to prevent double spend by the sender.
- In the syncParentToken function even if the token.GetWholeTokenValue(string(b))  return without error, the code will go in to the if clause
-  this causes the tokentype variable tt to be overwritten to that of TestTokenType.
- and when the token chain is trying to be synced the DB does not have entry fo valid whole RBT token with token tyep =3 as it should be 0 which is proper

**Comment by Allen-Cherian** [comment]
This issue has been addressed in PR #136
